version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - cp build/libs/bookapp-*.jar app.jar
artifacts:
  files:
    - app.jar
    - appspec.yml
    - scripts/**/*
cache:
  paths:
    - .gradle/**/*
